### ISSUE TITLE
[Needs confirmation and reproduce steps] Invincible Claudessa W

### ISSUE THREAD

**Issue by misterio202** [strife-community/strife-patches#120]
![image](https://github.com/user-attachments/assets/f9370321-7f2d-4ca9-a756-4eaf81afa18d)
Claudessa W doesn't have any visual effects on model and after healing allies. It's also doesn't provide bonuses from passive W to allies on heal.

**Comment by TheChiprel** [comment]
I can't reproduce it in practice. Can you provide match ID (can be found in replay section or on https://replayapi.playstrife.gg)?
