### ISSUE TITLE
All players should join single "General" chat channel.

### ISSUE THREAD

**Issue by TheChiprel** [strife-community/strife-patches#13]
Currently players join chat "General" channels according to language the chose. What's worse, those channels don't show in search unless you start typing "General Chat" to search bar. This creates illusion that there are less people in game than there actually is. With current community size it would rather be better if players were on one general channel.

**Comment by padjon** [comment]
Implemented by https://github.com/strife-community/strife-game/commit/bededc47645d223f58bc317e9b1752b0bffdf6dc
