### ISSUE TITLE
Youtube videos cant be played within the launcher anymore

### ISSUE THREAD

**Issue by padjon** [strife-community/strife-patches#16]
![image](https://github.com/user-attachments/assets/464f2acc-dd0f-4046-afe2-55af05ae9aba)
The links are all broken

**Comment by gabpoersch** [comment]
https://www.youtube.com/watch?v=c-B7Yr-Gy-E&list=PLSGwuxOIUJim5nTkbNGLxMGvhYCh5exeW

found the original playlist of videos but they are either outdated (in terms of description) or they simply don't exist

**Comment by padjon** [comment]
Figured out, the videos still exist but cant play anymore (rightclick a started video in the launcher). We should reestablish functionality to paly youtube videos in the client.

Increase the prio, because this is probably easy to fix but makes the experience for new players much worse
