### ISSUE TITLE
Disable currently unavaliable or broken options.

### ISSUE THREAD

**Issue by TheChiprel** [strife-community/strife-patches#19]
Here is not a final list of things to disable (not remove, just disable) until we fix or re-implement, since they are not working or broken (with tooltip "Work in progress" if applicable):

- Scrim Arena mode;
- Game quests and Player Ladder tabs on Account details;
- Boosters for feathers and craft materials;
- Gem purchase;
- Community guides button;
- First login prompt to link existing account.

**Comment by padjon** [comment]
- Clubs
