### ISSUE TITLE
Bottom account experience bar show incorrect data.

### ISSUE THREAD

**Issue by padjon** [strife-community/strife-patches#61]
Accountid 22.003
Witchblade
![Screenshot_20240921_121217_Discord](https://github.com/user-attachments/assets/3b587a62-9c41-4f69-bc92-350b69d405d0)

XP right now:
![Screenshot_20240921_113806_Chrome](https://github.com/user-attachments/assets/3c59fd91-3850-48cb-ab8a-086a8bbece11)

**Comment by TheChiprel** [comment]
It appears, that player gains experience fine, it is bottom experience indicator shows incorrect information.
